fix: add missing episode_time argument to render_scoreboard
render_scoreboard() requires 4 arguments:
- screen
- score1
- score2
- episode_time (was missing!)

Error was: TypeError: render_scoreboard() missing 1 required positional argument: 'episode_time'